### ISSUE TITLE
请问一下该数据集是用什么制作的

### ISSUE THREAD

**Issue by 969149731** [ShiratsuyuShigure/MLAENet-pytorch#2]
您好，请问一下该数据集是用什么制作的，想自己做一个苹果的这种数据集

**Comment by ShiratsuyuShigure** [comment]
这个数据集并不是我自己制作的，我是引用了他人制作的数据集进行实验，你可以访问readme中提供的链接进行询问

**Comment by ShiratsuyuShigure** [comment]
> 您好，请问一下该数据集是用什么制作的，想自己做一个苹果的这种数据集

这个数据集并不是我自己制作的，我是引用了他人制作的数据集进行实验，你可以访问readme中提供的链接进行询问
